on:
  push:
    branches:
      - main
  pull_request:

name: format-check

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: posit-dev/setup-air@v1

      - name: Check formatting with air
        run: air format --check .
