on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'devel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel'}
          # - {os: windows-latest, r: '4.0'}
          - {os: ubuntu-22.04,   r: 'release', rspm: "https://p3m.dev/cran/__linux__/jammy/latest"}
          - {os: ubuntu-22.04,   r: 'oldrel', rspm: "https://p3m.dev/cran/__linux__/jammy/latest"}


    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      # RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # vsni_LICENSE: ${{ secrets.vsni_LICENSE }}

    steps:
      - uses: actions/checkout@v4

      # - name: Create and populate .Renviron file
      #   run: echo vsni_LICENSE="vsni_LICENSE" >> ~/.Renviron


      # - name: Install data.table dependencies
      #   if: runner.os == 'Linux'
      #   run: sudo -s apt-get install zlib1g-dev pkg-config

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      # - name: Query dependencies
      #   run: |
      #     install.packages('remotes')
      #     saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
      #   shell: Rscript {0}

      # - name: Cache R packages
      #   if: runner.os != 'Windows'
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ env.R_LIBS_USER }}
      #     key: ${{ runner.os }}-r-${{ matrix.config.r }}-1-${{ hashFiles('.github/depends.Rds') }}
      #     restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-1-

      # - name: Install system dependencies
      #   if: runner.os == 'Linux'
      #   env:
      #     RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
      #   run: |
      #     Rscript -e "remotes::install_github('r-hub/sysreqs')"
      #     sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
      #     sudo -s eval "$sysreqs"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, asreml=?ignore, github::mjskay/ARTool
          needs: check

      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
